/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfazgrafica;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.InputMismatchException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mycompany.ExcepcionDatoValido;

/**
 *
 * @author Pavilion
 */


 public class PanelPrincipal extends javax.swing.JFrame {
    ArrayList <Integer> precios;
    ArrayList <Integer> cantidades;
    ArrayList <String> nombres;
    ArrayList <String> descripciones;
    ArrayList <String> codigos;
    ArrayList <String> materiales;
    ArrayList <String> EjemplosUso;
    ArrayList <Integer> ventasNum;
    DefaultTableModel modelo;

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        precios = new ArrayList<>();
        cantidades = new ArrayList<>();
        nombres = new ArrayList<>();
        descripciones = new ArrayList<>();
        codigos = new ArrayList<>();
        materiales = new ArrayList<>();
        EjemplosUso = new ArrayList<>();
        ventasNum = new ArrayList<>();
        
        precios.add((int)650);
        precios.add((int)2500);
        cantidades.add(8);
        cantidades.add(9);
        nombres.add("TORNILLO");
        nombres.add("GRIFO");
        descripciones.add("herramienta fundamental para la elaboracion de diferentes utensillos");
        descripciones.add("valcula mecanica");
        codigos.add("125B");
        codigos.add("125C");
        materiales.add("ACERO");
        materiales.add("BRONCE");
        EjemplosUso.add("unir dos piezas");
        EjemplosUso.add("en los lavaplatos");
        ventasNum.add(5);
        ventasNum.add(2);
    
        initComponents();
        modelo = new DefaultTableModel();
        
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE PRODUCTO");
        modelo.addColumn("CANTIDAD PRODUCTOS");
        modelo.addColumn("PRODUCTOS VENDIDOS");
        this.tablaProductos.setModel(modelo);
        String [] info = new String[4];
        for (int i=0; i<2; i++){
            info[0] = codigos.get(i);
            info[1] = nombres.get(i);
            info[2] = (cantidades.get(i)).toString();
            info[3] = (ventasNum.get(i)).toString();
            modelo.addRow(info);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        BotonClientes = new javax.swing.JButton();
        BotonProductos = new javax.swing.JButton();
        BotonVentas = new javax.swing.JButton();
        PanelContenedor = new javax.swing.JTabbedPane();
        PanelClientes = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelidCliente = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        PanelProductos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CampoBuscarProductoPorCodigo = new javax.swing.JTextField();
        //BotonBuscarProductoPorCodigo = new javax.swing.JButton();
        BotonBuscarProductoPorCodigo = new javax.swing.JButton();
        BotonMostrarEstadisticas = new javax.swing.JButton();
        PanelEnProductos = new javax.swing.JPanel();
        LabelDescripcion = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        LabelNombreProducto = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        LabelPrecio = new javax.swing.JLabel();
        LabelMaterial = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        txtmaterial = new javax.swing.JTextField();
        LabelEjemploUso = new javax.swing.JLabel();
        CampoEjemploUso = new javax.swing.JTextField();
        BotonEliminar = new javax.swing.JButton();
        BotonAdicionar = new javax.swing.JButton();
        BotonVaciarCamposDeTexto = new javax.swing.JButton();
        LabelCantidadProductos = new javax.swing.JLabel();
        CampoCantidadProductos = new javax.swing.JTextField();
        BotonVender = new javax.swing.JButton();
        BotonAgregar = new javax.swing.JButton();
        LabelCodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        verDetalleProducto = new javax.swing.JButton();
        LabelCodigo1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        PanelVentas = new javax.swing.JPanel();
        PanelInformacionVentas = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel13 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        PanelVentas1 = new javax.swing.JTabbedPane();
        PanelVentas12 = new javax.swing.JPanel();
        PanelVentas11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        BotonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/cliente.png"))); // NOI18N
        BotonClientes.setText("CLIENTES");
        BotonClientes.setFocusable(false);
        BotonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonClientes.setMaximumSize(new java.awt.Dimension(78, 60));
        BotonClientes.setMinimumSize(new java.awt.Dimension(78, 60));
        BotonClientes.setPreferredSize(new java.awt.Dimension(78, 60));
        BotonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonClientes);

        BotonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/carritoProductos.png"))); // NOI18N
        BotonProductos.setText("PRODUCTOS");
        BotonProductos.setFocusable(false);
        BotonProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProductosActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonProductos);

        BotonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/ManosVentas.png"))); // NOI18N
        BotonVentas.setText("VENTAS");
        BotonVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonVentas.setMaximumSize(new java.awt.Dimension(78, 60));
        BotonVentas.setMinimumSize(new java.awt.Dimension(78, 60));
        BotonVentas.setPreferredSize(new java.awt.Dimension(78, 60));
        BotonVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVentasActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonVentas);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        PanelClientes.setPreferredSize(new java.awt.Dimension(1308, 650));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("CLIENTES");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton7.setText("BUSCAR CLIENTE POR ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE COMPLETO");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabelidCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelidCliente.setText("ID");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("TIPO DE IDENTIFICACION");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("NUMERO DE IDENTIFICACION");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("NUMERO DE TELEFONO");

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton4.setText("GUARDAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("ACTUALIZAR");

        jButton6.setText("VACIAR CAMPO DE TEXTO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEDULA", "PASAPORTE", "TARJETA IDENTIDAD" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 312, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(181, 181, 181))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jTextField6)
                                    .addGap(68, 68, 68)))
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE COMPLETO", "TIPO IDENTIFICACION", "NUMERO IDENTIFICACION", "NUMERO DE TELEFONO", "N° COMPRAS REALIZADAS"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PanelContenedor.addTab("CLIENTES", PanelClientes);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("PRODUCTOS");

        CampoBuscarProductoPorCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CampoBuscarProductoPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarProductoPorCodigoActionPerformed(evt);
            }
        });

        BotonBuscarProductoPorCodigo.setText("BUSCAR PRODUCTOS POR CODIGO");
        BotonBuscarProductoPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarProductoPorCodigoActionPerformed(evt);
            }
        });

        BotonMostrarEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Imagenes/Estadisticas.png"))); // NOI18N
        BotonMostrarEstadisticas.setText("MOSTRAR ESTADÍSTICAS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoBuscarProductoPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonBuscarProductoPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BotonMostrarEstadisticas)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(CampoBuscarProductoPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonBuscarProductoPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonMostrarEstadisticas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CampoBuscarProductoPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarProductoPorCodigoActionPerformed(evt);
            }
        });

        PanelEnProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelDescripcion.setText("DESCRIPCIÓN");

        nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoActionPerformed(evt);
            }
        });

        LabelNombreProducto.setText("NOMBRE DEL PRODUCTO");

        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });

        LabelPrecio.setText("PRECIO");

        LabelMaterial.setText("MATERIAL   ELABORACIÓN");

        LabelEjemploUso.setText("EJEMPLO DE USO");

        CampoEjemploUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEjemploUsoActionPerformed(evt);
            }
        });

        BotonEliminar.setText("ELIMINAR");
        BotonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseClicked(evt);
            }
        });
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonAdicionar.setText("ADICIONAR");
        BotonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAdicionarActionPerformed(evt);
            }
        });

        BotonVaciarCamposDeTexto.setText("VACIAR CAMPO DE TEXTO");
        BotonVaciarCamposDeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVaciarCamposDeTextoActionPerformed(evt);
            }
        });

        LabelCantidadProductos.setText("CANTIDAD DE PRODUCTOS");

        CampoCantidadProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCantidadProductosActionPerformed(evt);
            }
        });

        BotonVender.setText("VENDER");
        BotonVender.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                BotonVenderActionPerformed(evt);
            }
        });

        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                BotonAgregarActionPerformed(evt);
            }
        });

        LabelCodigo.setText("CODIGO");

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        verDetalleProducto.setText("VER DETALLE DEL PRODUCTO");
        verDetalleProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verDetalleProductoMouseClicked(evt);
            }
        });
        verDetalleProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetalleProductoActionPerformed(evt);
            }
        });

        LabelCodigo1.setText("H-NECESARIAS");

        javax.swing.GroupLayout PanelEnProductosLayout = new javax.swing.GroupLayout(PanelEnProductos);
        PanelEnProductos.setLayout(PanelEnProductosLayout);
        PanelEnProductosLayout.setHorizontalGroup(
            PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoCantidadProductos)
                    .addGroup(PanelEnProductosLayout.createSequentialGroup()
                        .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreProducto)
                            .addComponent(LabelEjemploUso)
                            .addComponent(CampoEjemploUso)
                            .addComponent(txtdescripcion)
                            .addGroup(PanelEnProductosLayout.createSequentialGroup()
                                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelPrecio)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCodigo)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelEnProductosLayout.createSequentialGroup()
                                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtmaterial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCantidadProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelEnProductosLayout.createSequentialGroup()
                                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BotonAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelEnProductosLayout.createSequentialGroup()
                                        .addComponent(BotonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(BotonVaciarCamposDeTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19))
                            .addGroup(PanelEnProductosLayout.createSequentialGroup()
                                .addComponent(LabelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(verDetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelEnProductosLayout.setVerticalGroup(
            PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnProductosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(LabelNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCodigo)
                    .addGroup(PanelEnProductosLayout.createSequentialGroup()
                        .addComponent(LabelPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCodigo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCantidadProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelEjemploUso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoEjemploUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonAdicionar)
                    .addComponent(BotonVender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonVaciarCamposDeTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verDetalleProducto)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE PRODUCTO", "DISPONIBILIDAD", "ESTADO", "CANTIDAD DE PRODUCTOS", "N° DE PRODUCTOS VENDIDOS"
            }
        ));
        jScrollPane2.setViewportView(tablaProductos);

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addComponent(PanelEnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(PanelEnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelContenedor.addTab("PRODUCTOS", PanelProductos);

        PanelInformacionVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelInformacionVentas.setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);

        jLabel13.setBackground(new java.awt.Color(255, 204, 204));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel13.setText("INFORMACIÓN DE LAS VENTAS");
        jToolBar2.add(jLabel13);

        jButton12.setBackground(new java.awt.Color(255, 204, 255));
        jButton12.setText("PRODUCTO MAS VENDIDO");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton12);

        jButton13.setBackground(new java.awt.Color(255, 204, 204));
        jButton13.setText("PRODUCTO MENOS VENDIDO");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton13);

        PanelInformacionVentas.add(jToolBar2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout PanelVentas12Layout = new javax.swing.GroupLayout(PanelVentas12);
        PanelVentas12.setLayout(PanelVentas12Layout);
        PanelVentas12Layout.setHorizontalGroup(
            PanelVentas12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1311, Short.MAX_VALUE)
        );
        PanelVentas12Layout.setVerticalGroup(
            PanelVentas12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        PanelVentas1.addTab("PRODUCTO MAS VENDIDO", PanelVentas12);

        javax.swing.GroupLayout PanelVentas11Layout = new javax.swing.GroupLayout(PanelVentas11);
        PanelVentas11.setLayout(PanelVentas11Layout);
        PanelVentas11Layout.setHorizontalGroup(
            PanelVentas11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1311, Short.MAX_VALUE)
        );
        PanelVentas11Layout.setVerticalGroup(
            PanelVentas11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        PanelVentas1.addTab("PRODUCTO MENOS VENDIDO", PanelVentas11);

        javax.swing.GroupLayout PanelVentasLayout = new javax.swing.GroupLayout(PanelVentas);
        PanelVentas.setLayout(PanelVentasLayout);
        PanelVentasLayout.setHorizontalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInformacionVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelVentas1)
        );
        PanelVentasLayout.setVerticalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addComponent(PanelInformacionVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelVentas1))
        );

        PanelContenedor.addTab("VENTAS", PanelVentas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1311, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        PanelContenedor.addTab("tab3", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1311, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        PanelContenedor.addTab("tab4", jPanel5);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setText("jMenuItem5");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelContenedor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
 
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    public void BotonVaciarCamposDeTextoActionPerformed(java.awt.event.ActionEvent evt) {
        // Vaciar los campos de texto
        CampoBuscarProductoPorCodigo.setText("");
        txtcodigo.setText("");
        CampoCantidadProductos.setText("");
        txtprecio.setText("");
        nombreProducto.setText("");
        txtdescripcion.setText("");
        txtmaterial.setText("");
        CampoEjemploUso.setText("");
    }

    private void BotonClientesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        PanelContenedor.setSelectedComponent(PanelClientes);
    }                                             

    private void BotonProductosActionPerformed(java.awt.event.ActionEvent evt) {                                               
        PanelContenedor.setSelectedComponent(PanelProductos);
    }                                              

    private void CampoEjemploUsoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void CampoCantidadProductosActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void BotonVentasActionPerformed(java.awt.event.ActionEvent evt){                                                       
        PanelContenedor.setSelectedComponent(PanelVentas);
    }                                                      

    public void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt){
        if ((txtcodigo.getText()).equals("") || CampoCantidadProductos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DEBES MARCARLOS CAMPOS REQUERIDOS:\nCODIGO DEL PRODUCTO\nCANTIDAD DE PRODUCTOS ");
            return;
        }
        
        boolean codigoProductoEncontrado = false;
        try {
            if (Integer.parseInt(CampoCantidadProductos.getText()) <= 0){
                JOptionPane.showMessageDialog(null, "POR FAVOR INGRESE UNA CANTIDAD VÁLIDA");
                // Vaciar los campos de texto
                txtcodigo.setText("");
                CampoCantidadProductos.setText("");
                txtprecio.setText("");
                nombreProducto.setText("");
                txtdescripcion.setText("");
                txtmaterial.setText("");
                CampoEjemploUso.setText("");
                return;
            }
            int productosAgregar = Integer.parseInt(CampoCantidadProductos.getText());
            for (int i = 0; i < codigos.size(); i++) {
                if (txtcodigo.getText().equals(codigos.get(i))) {
                    codigoProductoEncontrado = true;
                    int nuevaCantidad = cantidades.get(i) + productosAgregar;

                    if (nuevaCantidad <= 0) {
                        JOptionPane.showMessageDialog(null, "POR FAVOR INGRESA UNA CANTIDAD VÁLIDA");
                        return; // Salir del método si no hay suficientes productos en stock
                    }
                    cantidades.set(i, nuevaCantidad); // Actualizar la cantidad disponible
                    modelo.setValueAt(nuevaCantidad, i, 2); // Actualizar la cantidad en la tabla
                    JOptionPane.showMessageDialog(null, "PRODUCTOS AGREGADOS EXITOSAMENTE");
        
                    break; // Salir del bucle después de encontrar el producto
                }
                
                }
                if (!codigoProductoEncontrado) {
                    JOptionPane.showMessageDialog(null, "EL PRODUCTO NO SE ENCUENTRA DISPONIBLE");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "DEBES AGREGAR UNA CANTIDAD NUMERICA!!");

        }catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null,"CANTIDAD INVALIDA!!");
        }

        // Vaciar los campos de texto
        txtcodigo.setText("");
        CampoCantidadProductos.setText("");
        txtprecio.setText("");
        nombreProducto.setText("");
        txtdescripcion.setText("");
        txtmaterial.setText("");
        CampoEjemploUso.setText("");
    }

    public void BotonBuscarProductoPorCodigoActionPerformed(java.awt.event.ActionEvent evt){
        if ((CampoBuscarProductoPorCodigo.getText()).equals("")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR DIGITA EL CODIGO DEL PRODUCTO A BUSCAR");
            return;
        }
        boolean codigoProductoEncontrado = false;
    
        for (int i = 0; i < codigos.size(); i++) {
            if (CampoBuscarProductoPorCodigo.getText().equals(codigos.get(i))) {
                codigoProductoEncontrado = true;
                JOptionPane.showMessageDialog(null, "INFORMACION DEL PRODUCTO:\nCÓDIGO: "+
                                codigos.get(i)+"\nNOMBRE: "+nombres.get(i)+"\nDESCRIPCIÓN: "+descripciones.get(i)+
                                "\nMATERIAL DE ELABORACION: "+materiales.get(i)+"\nEJEMPLO DE USO: "+EjemplosUso.get(i)+
                                "\nNUMERO DE VENTAS: "+ventasNum.get(i)+"\nCANTIDAD DISPONIBLE: "+cantidades.get(i)+"\n");
                break; // Salir del bucle después de encontrar el producto
            }
        }
        if (!codigoProductoEncontrado) {
            JOptionPane.showMessageDialog(null, "EL PRODUCTO NO SE ENCUENTRA DISPONIBLE");
        }

        // Vaciar los campos de texto
        CampoBuscarProductoPorCodigo.setText("");
}


    public void BotonVenderActionPerformed(java.awt.event.ActionEvent evt) {
        if ((txtcodigo.getText()).equals("") || CampoCantidadProductos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DEBES MARCARLOS CAMPOS REQUERIDOS:\nCODIGO DEL PRODUCTO*\nCANTIDAD DE PRODUCTOS*");
            return;
        }

        boolean codigoProductoEncontrado = false;
        try {
            if (Integer.parseInt(CampoCantidadProductos.getText()) <= 0){
                JOptionPane.showMessageDialog(null, "POR FAVOR INGRESE UNA CANTIDAD VÁLIDA");
                // Vaciar los campos de texto
                txtcodigo.setText("");
                CampoCantidadProductos.setText("");
                txtprecio.setText("");
                nombreProducto.setText("");
                txtdescripcion.setText("");
                txtmaterial.setText("");
                CampoEjemploUso.setText("");
                return;
            }
            int productosComprar = Integer.parseInt(CampoCantidadProductos.getText());
            for (int i = 0; i < codigos.size(); i++) {
                if (txtcodigo.getText().equals(codigos.get(i))) {
                    codigoProductoEncontrado = true;
                    int nuevaCantidad = cantidades.get(i) - productosComprar;
                    if (nuevaCantidad < 0) {
                        JOptionPane.showMessageDialog(null, "No hay suficientes productos en stock");
                        return; // Salir del método si no hay suficientes productos en stock
                    }
                    cantidades.set(i, nuevaCantidad); // Actualizar la cantidad disponible
                    int nuevaVenta = ventasNum.get(i) + productosComprar;
                    ventasNum.set(i, nuevaVenta); // Actualizar la cantidad vendida
                    modelo.setValueAt(nuevaCantidad, i, 2); // Actualizar la cantidad en la tabla
                    modelo.setValueAt(nuevaVenta, i, 3); // Actualizar la cantidad vendida en la tabla
        
                    if (nuevaCantidad == 0) {
                        // Si la cantidad disponible es 0, puedes eliminar la fila de la tabla
                        modelo.removeRow(i);
                        codigos.remove(i);
                        nombres.remove(i);
                        descripciones.remove(i);
                        materiales.remove(i);
                        EjemplosUso.remove(i);
                        ventasNum.remove(i);
                        cantidades.remove(i);
                    }
                    JOptionPane.showMessageDialog(null, "PRODUCTOS VENDIDOS EXITOSAMENTE");
                    break; // Salir del bucle después de encontrar el producto
                }
                
                }
                if (!codigoProductoEncontrado) {
                    JOptionPane.showMessageDialog(null, "EL PRODUCTO NO SE ENCUENTRA DISPONIBLE");
            }
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null,"CANTIDAD INVALIDA!!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "DEBES AGREGAR UNA CANTIDAD NUMERICA!!");

        }

        // Vaciar los campos de texto
        txtcodigo.setText("");
        CampoCantidadProductos.setText("");
        txtprecio.setText("");
        nombreProducto.setText("");
        txtdescripcion.setText("");
        txtmaterial.setText("");
        CampoEjemploUso.setText("");
    }


        private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
            PanelVentas1.setSelectedComponent(PanelVentas12);
        }                                         

        private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
            PanelVentas1.setSelectedComponent(PanelVentas11);
        }                                         

        private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {                                          
            // TODO add your handling code here:
        }                                         

        private void CampoBuscarProductoPorCodigoActionPerformed(java.awt.event.ActionEvent evt){                                          
            // TODO add your handling code here:
        }                                         

        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
            // TODO add your handling code here:
        }                                          

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
            // TODO add your handling code here:
        }                                           

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        }                                        

        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
            // TODO add your handling code here:
        }                                           

        private void BotonEliminarMouseClicked(java.awt.event.MouseEvent evt) {                                           
        
    // TODO add your handling code here:
        }                                          

        private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                              
            // TODO add your handling code here:
            int fila = tablaProductos.getSelectedRow();
            if(fila>=0){
                modelo.removeRow(fila);
                precios.remove(fila);
                cantidades.remove(fila);
                nombres.remove(fila);
                descripciones.remove(fila);
                codigos.remove(fila);
                materiales.remove(fila);
                EjemplosUso.remove(fila);
                ventasNum.remove(fila);

                // Vaciar los campos de texto en caso de que el usuario los rellene
                txtcodigo.setText("");
                CampoCantidadProductos.setText("");
                txtprecio.setText("");
                nombreProducto.setText("");
                txtdescripcion.setText("");
                txtmaterial.setText("");
                CampoEjemploUso.setText("");

            }
            else{
                JOptionPane.showMessageDialog(null, "Seleccionar fila");
                // Vaciar los campos de texto en caso de que el usuario los rellene
                txtcodigo.setText("");
                CampoCantidadProductos.setText("");
                txtprecio.setText("");
                nombreProducto.setText("");
                txtdescripcion.setText("");
                txtmaterial.setText("");
                CampoEjemploUso.setText("");
            }
        }                                             

    private void nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              


    public void BotonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if ((txtcodigo.getText()).equals("") || nombreProducto.getText().equals("") || CampoCantidadProductos.getText().equals("") || txtprecio.getText().equals("") || txtdescripcion.getText().equals("") || txtmaterial.getText().equals("") || CampoEjemploUso.getText().equals("")){
            JOptionPane.showMessageDialog(null, "DEBES MARCAR TODOS LOS CAMPOS!!!");
        }
        else{
            boolean cantidadValida = true, precioValido = true;
            try{
                cantidades.add(Integer.parseInt(CampoCantidadProductos.getText()));
                if ((Integer.parseInt(CampoCantidadProductos.getText())) <= 0){
                    throw new ExcepcionDatoValido("");
                }
            }catch(NumberFormatException e){
                cantidadValida = false;
                JOptionPane.showMessageDialog(null, "DEBES AGREGAR UNA CANTIDAD NUMERICA!!");
            }catch(ExcepcionDatoValido e){
                cantidadValida = false;
                JOptionPane.showMessageDialog(null,"CANTIDAD INVALIDA!!");
            }
            try{
                precios.add(Integer.parseInt(txtprecio.getText()));
                if ((Integer.parseInt(txtprecio.getText())) <= 0){
                    throw new ExcepcionDatoValido("");
                }
            }catch(NumberFormatException e){
                precioValido = false;
                JOptionPane.showMessageDialog(null, "DEBES AGREGAR UN PRECIO NUMERICO!!");
            }catch(ExcepcionDatoValido e){
                precioValido = false;
                JOptionPane.showMessageDialog(null,"PRECIO INVALIDO!!");
            }

            if (cantidadValida == true && precioValido == true){
                String [] info = new String[4];
                info[0] = txtcodigo.getText();
                info[1] = nombreProducto.getText();
                info[2] = CampoCantidadProductos.getText();
                info[3] = "0";
                nombres.add(nombreProducto.getText());
                descripciones.add(txtdescripcion.getText());
                codigos.add(txtcodigo.getText());
                materiales.add(txtmaterial.getText());
                EjemplosUso.add(CampoEjemploUso.getText());
                ventasNum.add((int)0);
                modelo.addRow(info);
            }
        }

        // Vaciar los campos de texto
        txtcodigo.setText("");
        txtprecio.setText("");
        CampoCantidadProductos.setText("");
        nombreProducto.setText("");
        txtdescripcion.setText("");
        txtmaterial.setText("");
        CampoEjemploUso.setText("");
    }
 
        // TODO add your handling code here:
        
                                              

    private void verDetalleProductoMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:

    }                                               

    private void verDetalleProductoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();
        if(fila>=0){
            JOptionPane.showMessageDialog(null, "PRECIO: " + precios.get(fila) + "\nCANTIDADES: " + cantidades.get(fila) + "\nNOMBRE: " + nombres.get(fila) + "\nDESCRIPCION: " + descripciones.get(fila) + "\nCODIGO: " + codigos.get(fila) + "\nMATERIAL DE ELABORACION: " + materiales.get(fila) + "\nEJEMPLO DE USO: "+ EjemplosUso.get(fila));

       }else{
           JOptionPane.showMessageDialog(null, "Seleccionar fila para ver detalles");
       }
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonAdicionar;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonMostrarEstadisticas;
    private javax.swing.JButton BotonProductos;
    private javax.swing.JButton BotonVender;
    private javax.swing.JButton BotonVentas;
    private javax.swing.JTextField CampoBuscarProductoPorCodigo;
    private javax.swing.JTextField CampoCantidadProductos;
    private javax.swing.JTextField CampoEjemploUso;
    private javax.swing.JLabel LabelCantidadProductos;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelCodigo1;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelEjemploUso;
    private javax.swing.JLabel LabelMaterial;
    private javax.swing.JLabel LabelNombreProducto;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JTabbedPane PanelContenedor;
    private javax.swing.JPanel PanelEnProductos;
    private javax.swing.JPanel PanelInformacionVentas;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelVentas;
    private javax.swing.JTabbedPane PanelVentas1;
    private javax.swing.JPanel PanelVentas11;
    private javax.swing.JPanel PanelVentas12;
    private javax.swing.JButton BotonVaciarCamposDeTexto;
    //private javax.swing.JButton BotonBuscarProductoPorCodigo;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton BotonBuscarProductoPorCodigo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelidCliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    //private javax.swing.JTextField CampoBuscarProductoPorCodigo;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtmaterial;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JButton verDetalleProducto;
    // End of variables declaration                   
}
